import Head from "next/head";
import Layout, { siteTitle } from "../components/layout";
import utilStyles from "../styles/utils.module.css";
import { getCategories, getSortedPostsData } from "../lib/posts";
import React, { useEffect } from "react";
import Link from "next/link";
import Categories from "../components/posts/categories";

export async function getStaticProps() {
  const categories = getCategories();
  const categoriesObj = {};
  categories.forEach((fileName) => {
    const postsData = getSortedPostsData(fileName);
    categoriesObj[fileName] = postsData;
  });
  return {
    props: {
      categoriesObj,
    },
  };
}

export default function Home({categoriesObj}) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   <Layout>
    <Categories categoriesObj= {categoriesObj}></Categories>
   </Layout>
    </div>
  )
}


// export default function Home() {
//   useEffect(() => {
//     console.log(categories);
//   }, []);
//   return (
//     <>
//       <Layout home>
//         <Head>
//           <title>{siteTitle}</title>
//         </Head>
//         <Categories />
//         <section className={utilStyles.headingMd}>
//           <p>
//             Hello, I’m <strong>Shu</strong>. I’m a software engineer and a
//             translator (English/Japanese). You can contact me on{" "}
//             <a href="https://twitter.com/chibicode">Twitter</a>.
//           </p>
//           <p>
//             (This is a sample website - you’ll be building a site like this in{" "}
//             <a href="https://nextjs.org/learn">our Next.js tutorial</a>.)
//           </p>
//         </section>

//       </Layout>
//     </>
//   );
// }
